name: we_neighbour
description: A Flutter login screen for the We Neighbour app.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Add any required third-party libraries below (currently not used)
  google_fonts: ^6.2.1 # Optional: If you want to use Google Fonts
  flutter_svg: ^2.0.9  # Optional: For SVG images if required

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/white.png
    - assets/images/facebook.png
    - assets/images/google.png
    - assets/images/twitter.png
    - assets/images/logo.png
    - assets/images/logo.png
    - assets/icons/amenities.png
    - assets/icons/visitor.png
    - assets/icons/calendar.png
    - assets/icons/maintenance.png
    - assets/icons/bills.png
    - assets/icons/chat.png
    - assets/images/painting.jpg
    - assets/images/plumbing.jpg
    - assets/images/carpentry.jpg

  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700

