name: we_neighbour
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+4
  shared_preferences: ^2.0.8
  flutter_carousel_slider: ^1.0.8
  path_provider: ^2.0.11
  path: ^1.8.0
  google_fonts: ^4.0.0
  provider: ^6.0.0
  cupertino_icons: ^1.0.8
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # Added for custom app icon support

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo1.png"  # Path to your custom icon
  adaptive_icon_background: "#ffffff"  # Optional for Android adaptive icons
  adaptive_icon_foreground: "assets/logo1.png"

flutter:
  uses-material-design: true

  assets:
    - assets/logo1.png  # Ensure this file exists in your project
