name: we_neighbour
description: A Flutter app for the We Neighbour community.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2  # Added provider package
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.9
  flutter_carousel_slider: ^1.0.8
  cupertino_icons: ^1.0.8
  badges: ^3.1.2
  image_picker: ^1.0.4
  shared_preferences: ^2.2.0
  path_provider: ^2.1.1
  path: ^1.8.3
  qr_flutter: ^4.1.0
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.2.2
  share_plus: ^7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^1.3.0 # Check for the latest version
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/white.png
    - assets/images/facebook.png
    - assets/images/google.png
    - assets/images/twitter.png
    - assets/images/logo.png
    - assets/icons/amenities.png
    - assets/icons/visitor.png
    - assets/icons/calendar.png
    - assets/icons/maintenance.png
    - assets/icons/bills.png
    - assets/icons/chat.png
    - assets/images/painting.jpg
    - assets/images/plumbing.jpg
    - assets/images/carpentry.jpg
    - assets/images/calendar_icon.png
    - assets/images/amenities_icon.png
    - assets/images/health_icon.png
    - assets/images/we_neighbour_logo.png
    - assets/images/logo_dark.png

  # Uncomment and update this section if you want to use custom fonts
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700

