name: my_apartment_app
description: A residential management app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5  # For state management
  shared_preferences: ^2.0.15  # For local storage
  http: ^0.13.4  # For API calls
  cached_network_image: ^3.2.1  # For image caching
  flutter_svg: ^1.1.0  # For SVG support
  intl: ^0.17.0  # For date formatting

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/
    - assets/logo.png

  fonts:
    - family: CustomFont
      fonts:
        - asset: assets/fonts/custom_font.ttf