// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMtEICL2cF_UtiOoORQvFs-kDH4A1w_yY',
    appId: '1:24541811517:web:1926da584e4592a21eeb54',
    messagingSenderId: '24541811517',
    projectId: 'weneighbour-c2e23',
    authDomain: 'weneighbour-c2e23.firebaseapp.com',
    databaseURL: 'https://weneighbour-c2e23-default-rtdb.firebaseio.com',
    storageBucket: 'weneighbour-c2e23.firebasestorage.app',
    measurementId: 'G-HWZ5ZWW6LK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaOLb9uF8TAzAlPk2S5mP8-5rHNoB1bJ8',
    appId: '1:24541811517:android:d877671d906903ad1eeb54',
    messagingSenderId: '24541811517',
    projectId: 'weneighbour-c2e23',
    databaseURL: 'https://weneighbour-c2e23-default-rtdb.firebaseio.com',
    storageBucket: 'weneighbour-c2e23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCpUmbQSO6gRTTwVVuLzeyv8Z0q6Jzmqo',
    appId: '1:24541811517:ios:bc61dac448c1b3101eeb54',
    messagingSenderId: '24541811517',
    projectId: 'weneighbour-c2e23',
    databaseURL: 'https://weneighbour-c2e23-default-rtdb.firebaseio.com',
    storageBucket: 'weneighbour-c2e23.firebasestorage.app',
    androidClientId: '24541811517-3fi0ini6hrpg6ao0bgr2tvv06tncpggq.apps.googleusercontent.com',
    iosClientId: '24541811517-nijlj66v9qgais5fboamaun6j91p577t.apps.googleusercontent.com',
    iosBundleId: 'com.example.newapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCpUmbQSO6gRTTwVVuLzeyv8Z0q6Jzmqo',
    appId: '1:24541811517:ios:bc61dac448c1b3101eeb54',
    messagingSenderId: '24541811517',
    projectId: 'weneighbour-c2e23',
    databaseURL: 'https://weneighbour-c2e23-default-rtdb.firebaseio.com',
    storageBucket: 'weneighbour-c2e23.firebasestorage.app',
    androidClientId: '24541811517-3fi0ini6hrpg6ao0bgr2tvv06tncpggq.apps.googleusercontent.com',
    iosClientId: '24541811517-nijlj66v9qgais5fboamaun6j91p577t.apps.googleusercontent.com',
    iosBundleId: 'com.example.newapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMtEICL2cF_UtiOoORQvFs-kDH4A1w_yY',
    appId: '1:24541811517:web:1998755e2f3629661eeb54',
    messagingSenderId: '24541811517',
    projectId: 'weneighbour-c2e23',
    authDomain: 'weneighbour-c2e23.firebaseapp.com',
    databaseURL: 'https://weneighbour-c2e23-default-rtdb.firebaseio.com',
    storageBucket: 'weneighbour-c2e23.firebasestorage.app',
    measurementId: 'G-49FDP9NLE5',
  );

}