// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaOLb9uF8TAzAlPk2S5mP8-5rHNoB1bJ8',
    appId: '1:24541811517:android:0517dccba6b79b781eeb54',
    messagingSenderId: '24541811517',
    projectId: 'weneighbour-c2e23',
    databaseURL: 'https://weneighbour-c2e23-default-rtdb.firebaseio.com',
    storageBucket: 'weneighbour-c2e23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCpUmbQSO6gRTTwVVuLzeyv8Z0q6Jzmqo',
    appId: '1:24541811517:ios:f06a45c833433da61eeb54',
    messagingSenderId: '24541811517',
    projectId: 'weneighbour-c2e23',
    databaseURL: 'https://weneighbour-c2e23-default-rtdb.firebaseio.com',
    storageBucket: 'weneighbour-c2e23.firebasestorage.app',
    androidClientId: '24541811517-47nhe1i73d384jbep45oeb48bddc0hu6.apps.googleusercontent.com',
    iosClientId: '24541811517-9rd504g71qggut24f32hta4qbrfjfjql.apps.googleusercontent.com',
    iosBundleId: 'com.example.weNeighbourProject',
  );
}
