name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Java (required for Android builds)
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0' # Use the version compatible with your project
          channel: 'stable'

      # Get dependencies
      - name: Get Flutter dependencies
        run: flutter pub get

      # Run code analysis (optional but recommended)
      - name: Run Flutter analyze
        run: flutter analyze

      # Run tests (this will execute widget_test.dart)
      - name: Run tests
        run: flutter test

      # Build APK (optional, for Android)
      - name: Build APK
        run: flutter build apk --debug

      # Upload APK using the updated v4 action
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: build/app/outputs/flutter-apk/app-debug.apk
          if-no-files-found: error # Optional: fail the step if no files are found